# Generated by Django 4.1.1 on 2022-10-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0002_alter_estudiante_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregable",
            name="entregado",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="entregable",
            name="fechaDeEntrega",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="entregable",
            name="nombre",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
