# Generated by Django 4.1.1 on 2022-10-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0003_entregable_entregado_entregable_fechadeentrega_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entregable",
            old_name="fechaDeEntrega",
            new_name="fecha",
        ),
    ]
